import { StoreVitalProvider } from "@/components/contexts/storeVital";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./themeRegistory";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "mui" }}>
          <StoreVitalProvider>{children}</StoreVitalProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
